### ISSUE TITLE
Monitor Costs

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#3]
We will needs some way to monitor the costs. Right now it seems free to run, but we should set up billing alerts.

**Comment by falquaddoomi** [comment]
There are currently some default billing alerts set up here: https://console.cloud.google.com/billing/018134-7FE24A-5483F1/budgets?organizationId=1001406549565&project=gap-som-dbmi-geneplx-app-p0n

(Let me know if you don't have access and I can attempt to get it for you.)

(Note that there's a second project on the billing account, `gap-som-dbmi-geneplx-cpl-3rd`, which will likely never have costs since we'll likely never use it. John Finigan from SOM-IT sets up these "control plane" projects -- "cpl" is short for that -- to, e.g., host repos for IaC deployment, but I find it easier to manage IaC locally.)

The current budget cap is $200/mo, and we should receive alerts at 5%, 10%, etc. up to 100%. Our forecast for the end of this month is $1.62, most of which goes toward storing the cloud function images in the artifact registry. At the moment it looks like the alerts go to me and someone in OIT, and I don't have permission to change it, but I'm sure John will grant them if I ask.

**Comment by ChristopherMancuso** [comment]
I can see the billing alerts and this all sounds good to me. $1.62 a month is pretty good so far!. I would say we could close this issue.
