### ISSUE TITLE
adherence to NAR guidelines

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/geneplexus-app-v2#40]
NAR has guidelines for submission at [Web Server Issue Guidelines](https://academic.oup.com/nar/pages/submission_webserver). Some main takeaways from this

1. provide a cookie consent
2. cannot use any tracking cookies. Does that mean we can't get any usage metrics? Does GCP function do this automatically? 
3. need to make help/tutorial pages
4. landing page must have a free access statement or a license 
5. Can't be a new method, so that means we need to include BioGRID and IMO and only stick to the 6 model species (currently what we are doing but this precludes us to expanding before publication I believe)
6. Can't use Flash and/or Java plugins due to security risks (not sure if we do this or not)

**Comment by vincerubinetti** [comment]
For 1), let's reference text from mygeneset.info and monarch.org.

For 2), we don't use any _cookies_, but we do use `localStorage` for remembering recent analysis inputs, as added in #38 in https://github.com/krishnanlab/geneplexus-app-v2/pull/38/commits/20a0e2b83236c5b587d8fc597695b8705e63676a. For GDPR, I think this is still a legal gray area. For a journal submission, I think using `localStorage` (without sending it to our own servers to record it) is well within the actual spirit/intent of the rule, which is to not track your user's data without their consent. However, if you go to our Google Cloud console, you'll see logs of request for the past X number of days. I don't remember if those include IP addresses, but it will show the input genes the function was called with. So we might want a disclosure somewhere. We haven't added Google Analytics yet, but if we do that, that definitely requires disclosure.

For 3) and 4), that sounds like a good opportunity to put something on the home page.

For 6), definitely not.

**Comment by ChristopherMancuso** [comment]
For 1) we also have some things on the live version of the web server too. I will need to go and check all the data source pages (i.e. STRING, Monarch, BioGRID) to make sure there licenses haven't changed either for us to reuse their data.

**Comment by vincerubinetti** [comment]
I was thinking of putting something like this at the top of the About page under a "Terms of Service" section:

> For the user's convenience, this web application saves certain information locally, such as recent analysis inputs. This data only exists locally on the user's device, and is not sent to the developers of GenePlexus or any other party. By using this web application, you consent to these terms.

If we end up adding analytics, we can use something like this:

> This web application tracks user behavior such as navigation and clicks through the use of Google Analytics. These background scripts/services take significant steps to remove identifying information from the data they collect to ensure anonymity. The developers of GenePlexus pledge to never inspect or disclose any private, identifying information collected, and to only use it for the purposes of improving GenePlexus.

**Comment by vincerubinetti** [comment]
Let me go through the guidelines one by one (the ones that apply to me or that I can answer). Feel free to include or reference this in the submission or if you get reviewer push back.

- ✅ _be functional on the date of the proposal submission. Access to the server must be through a web browser.
  use the HTTPS protocol and run on the http standard port (443)_

- ✅ _provide a cookie consent form when cookies are used._
  We're not using [cookies](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie), we're using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). So, taken literally, we're definitely okay here. Even if the spirit of the guideline is to include `localStorage`, we still have a disclosure on the `/about` page under "Terms of Use"

- ✅ _include a simple mechanism to try out sample data provided by the authors, for example, a button for automatic loading of the data. Sample data must be accessible to users so that they can confirm data formatting requirements._
  We have a prominent "Example" button for loading an example geneset.

- ❓/📋 _contain help pages and/or a tutorial with links to sample output that performs interactively in the same way as real output. The help pages must include information on how to interpret the results returned by the web server._
  With the presence of the "Example" button, and when we add links to the package ReadTheDocs next to each part of the results, we already meet the intent of this guideline without having a help page. I'd also argue this is just a misguided rule, and that help pages are not a very effective way to help users compared to other methods (like putting explanations/links right next to the things that need them rather than on a separate page). However, I'd be willing to put a very brief explanation of what the web app can do and how to use it on the help page, including mentioning the "Example" button and ReadTheDocs links next to results so they know the user knows where to find the help they need. This guideline doesn't explicitly say we need screenshots/videos of the UI or explaining every button the user needs to click, and I really don't like do that because it's a pain to make, it gets out of sync with changes to the real UI quickly leading to confusion, and is probably not read by enough users to be worth the effort.

- ✅ _keep every user's submitted data private and not viewable by anyone other than the user or those given permission by the user._

- ✅ _provide a web link to the results if the website is not able to return results immediately. The link should be provided at the time of data submission and allow the user to bookmark and access the results later. Ideally, the link will report the status of the job (queued, running, or finished). Any request for an email must state that it is optional._
  I think we _technically_ don't provide this. Right after submitting a job, the user can save their inputs so they can at least come back later and start their analysis without having to input everything again. Also if they happen to accidentally refresh the page after submitting, the inputs will be saved and the analysis will start again. Also we save their most recent analysis inputs on their device, so they can restart analyses from there. All of these things involve just saving the inputs and re-running the analysis. But given that analyses run so quickly, I believe we meet the intent of this guideline, which is to make the webapp more user-friendly.

- 📋 _provide a clear benefit over similar applications or over using R packages_
  This seems like a good sentence or two to add to the homepage.

- ✅/📋 _provide rich data output (e.g. hyperlinks and visualisations)_
  We certainly have rich results. We should add high-level screenshots to the homepage to give a _rough idea_ of what the results look like, like this homepage: https://adage.greenelab.com/?model=1

- ✅/📋 _have a free access statement or a license link on the landing page_
  We have a license/terms of use on the about page, but we could perhaps link to those sections in the footer so they're accessible from every page, including the home page

- ✅ _not require users to log in, to register, or to leave an email address unless they handle sensitive human data (see below). Any registration must be optional e.g. for data sharing or access restriction to the user's own data._

- ✅ _not be restricted to a single (or few) species except for humans and common model organisms_

- ✅ _not require excessive data preprocessing with other tools (e.g. by creating Rdata frames) before it can be used.
  cover single steps in the middle of a pipeline._

- ✅ _not be updates/enhancements/copies of web servers which have been published within the last two years_

- ✅ _not use Flash and/or Java plugins due to security risks_

- ✅ _not use tracking cookies_

- ✅/📋 _provide a help page which contains a comprehensive list of the web services available along with a clear description and the access URL of each._
  I'll add links to the package and such on the about page.

**Comment by ChristopherMancuso** [comment]
Thanks for laying that all out! My thoughts on the clip board items

- I think the help/tutorial submission requirement is misguided and not helpful either, and as you say it is very hard to keep a full tutorial on the help page up-to-date. I think your suggestion of adding links (possibly inside tooltips) next to each type of result that link to PyGenePlexus documentation covers the second part of this as well. 
- We have spent a long time optimizing the google functions and backend data so that results are returned in very little time, so I don't think we need to link to the results
- I think we can add this to the homepage, but on there mostly saying what the main features are. In the one-page submission due in Dec, I can go into more comparisons with other tools.
- Agreed screenshots of results on the home page is a good idea
- License, terms of use and citations could be god to have at the footer of every page
- Links to the python package and published manuscripts should be all that is needed.
